### ISSUE TITLE
the install action for zabbix 5.0 on centos/redhat 7 is wrong

### ISSUE THREAD

**Issue by taleintervenor** [voxpupuli/puppet-zabbix#731] opened 2020-12-15 02:22 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet5-release-5.0.0-7
- Ruby: 
- Distribution: CentOS Linux release 7.7.1908
- Module version: 8.0.0

## How to reproduce (e.g Puppet code you use)
class { 'zabbix':
      zabbix_version  => $version,
}
set $version = 5.0
## What are you seeing
puppet zabbix module try to install zabbix-web-mysql
## What behaviour did you expect instead
according to zabbix official install instruction, only on centos/redhat 8 can find the zabbix-web-mysql package. when it is centos7, you need to install centos-release-scl and then install zabbix-web-mysql-scl package from the scl repo.
## Output log
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install zabbix-web-mysql' returned 1: Error: Nothing to do
Error: /Stage[main]/Zabbix::Web/Package[zabbix-web-mysql]/ensure: change from 'purged' to 'latest' failed: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install zabbix-web-mysql' returned 1: Error: Nothing to do (corrective)

**Comment by jameskirsop** [comment] 2021-01-21 21:16
This is a duplicate of #689 and the particular concern is being addressed in the open issue.

**Closed** 2021-03-14 20:49 UTC
