### ISSUE TITLE
zabbix-agentd can't start on CentOS 6.x

### ISSUE THREAD

**Issue by xdexter** [voxpupuli/puppet-zabbix#264] opened 2016-08-18 21:05 UTC
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 1.8.7
- Distribution: CentOS release 6.8 (Final)
- Module version: v2.4.0

### How to reproduce (e.g Puppet code you use)
include zabbix::agent

### What are you seeing
Problem 1: The service zabbix-agent on Centos 6.x have the binary in "/usr/sbin/zabbix_agentd", but template the module (https://github.com/voxpupuli/puppet-zabbix/blob/master/templates/zabbix-agent-redhat.init.erb) use the path "/usr/local/sbin/zabbix_agentd". 

Problem 2: In template init.d (https://github.com/voxpupuli/puppet-zabbix/blob/master/templates/zabbix-agent-redhat.init.erb) have syntax error on "OPTS" variable, the caracter "-c" are in variable (OPTS="-c <%= @agent_configfile_path %>") and daemon (daemon "$ZABBIX_BIN -c $OPTS").

### What behaviour did you expect instead
service start works

### Output log
Problem 1:
Error: Could not start Service[zabbix-agent]: Execution of '/sbin/service zabbix-agent start' returned 5: /usr/local/sbin/zabbix_agentd not installed!
Error: /Stage[main]/Zabbix::Agent/Service[zabbix-agent]/ensure: change from stopped to running failed: Could not start Service[zabbix-agent]: Execution of '/sbin/service zabbix-agent start' returned 5: /usr/local/sbin/zabbix_agentd not installed!

Problem 2:
Iniciando o Zabbix Agent: zabbix_agentd [32380]: cannot open config file [-c]: [2] No such file or directory

### Any additional information you'd like to impart
After correct both problems de service works.

**Comment by bastelfreak** [comment] 2016-08-18 21:14
ugh :( Thanks for reporting this. Do you think you're able to provide a patch for this?

**Comment by xdexter** [comment] 2016-08-18 22:50
Hello @bastelfreak,

I think that best solution are use script default from package zabbix-agentd from CentOS, see please: https://github.com/voxpupuli/puppet-zabbix/pull/265. I already tested and working.

**Comment by xdexter** [comment] 2016-08-18 22:52
Ah, or remove the code in startup.pp:

elsif $::osfamily in ['Debian', 'RedHat'] {
    # Currently other osfamily without systemd is not supported
    $osfamily_downcase = downcase($::osfamily)
    file { "/etc/init.d/${name}":
      ensure  => file,
      mode    => '0755',
      content => template("zabbix/${name}-${osfamily_downcase}.init.erb"),
    }

Do you decide, :)

**Comment by shaunrampersad** [comment] 2016-10-10 11:23
Possible solution for problem1: 
Change the template 
from
```
ZABBIX_BIN="/usr/local/sbin/zabbix_agentd"
```
to 
```
ZABBIX_BIN=`which zabbix_agentd`
```

**Comment by bastelfreak** [comment] 2016-10-10 11:51
Hi,
I'm not sure if `/usr/local/sbin/zabbix_agentd` is valid on any RHEL clone. I checked my CentOS 6 and 7 boxes and both have `/usr/sbin/zabbix_agentd`. However, I like the proposal from @shaunrampersad, this should be the most flexible.

**Comment by bastelfreak** [comment] 2016-10-10 11:52
@shaunrampersad you opened the PR against your fork, not sure if this was intended. Could you open it against the Vox Pupuli repo as well?

**Comment by killermoehre** [comment] 2016-10-10 11:57
IMHO it should be `ZABBIX_BIN="$(type -P zabbix_agent)"`. Less forking (`type` is inbuild) and backticks are somehow discouraged due to nesting issues (and they look ugly).

**Comment by shaunrampersad** [comment] 2016-10-10 12:29
@bastelfreak , happy to do the PR to Vox Pupuli. 
I did it on mine to test before I submitted to Vox. 

@killermoehre , havent used type -P. I'm no expert on this, but looks like it works as well. Happy to change to this and submit PR if everyone is happy ?

**Comment by shaunrampersad** [comment] 2016-10-10 15:06
@bastelfreak , submitted a PR anyways.
I've tested and agent starts up now.

**Comment by shaunrampersad** [comment] 2016-10-11 11:47
I've also fixed the zabbix-server-redhat.init.erb. 

```
ZABBIX_BIN="$(type -P zabbix_server)"
OPTS="<%= @server_configfile_path %>"
```

**Comment by bastelfreak** [comment] 2016-10-11 12:01
@xdexter can you confirm that the changes we merged in https://github.com/voxpupuli/puppet-zabbix/pull/291 work? Than I can kick of a nother release of the module.

**Comment by admont** [comment] 2016-10-11 14:07
Yes, it works now. Thank you!

**Comment by bastelfreak** [comment] 2016-10-11 14:22
okay perfect. travis is currently busy, not sure if we can kick out a release today, I will add it to the queue.

**Closed by bastelfreak** 2016-10-11 14:22 UTC

**Comment by xdexter** [comment] 2016-10-11 17:02
Perfect, thank you all.
